return {
	"lewis6991/gitsigns.nvim",
	event = { "BufReadPre", "BufNewFile" },
	opts = {
		signs = {
			add = { text = "▎" },
			change = { text = "▎" },
			delete = { text = "▁" },
			topdelete = { text = "▔" },
			changedelete = { text = "▎" },
			untracked = { text = "▎" },
		},
		numhl = true,
		linehl = false,
		word_diff = false,
		max_file_length = 40000,
		update_debounce = 100,
		preview_config = {
			border = "rounded",
			style = "minimal",
			relative = "cursor",
			row = 0,
			col = 1,
		},
		current_line_blame = false,
		current_line_blame_opts = {
			virt_text = true,
			virt_text_pos = "eol",
			delay = 300,
			ignore_whitespace = false,
		},
		signcolumn = true,
		watch_gitdir = {
			follow_files = true,
		},
		attach_to_untracked = true,
		sign_priority = 6,
		status_formatter = nil,
		diff_opts = {
			algorithm = "myers",
			internal = true,
			indent_heuristic = true,
		},
	},
}
